#!/usr/bin/env node
/**
 * sync-tokens — generate src/app/design-tokens.generated.css from TS tokens.
 *
 * Runs with Node's --experimental-strip-types (Node 22.6+) so the TS source
 * can be imported directly without tsx / ts-node / a build step.
 *
 *   npm run sync-tokens           # regenerate
 *   npm run sync-tokens:check     # exit 1 if generated file is stale
 *
 * Source of truth: design-system/tokens/colors.ts
 * Output:          src/app/design-tokens.generated.css
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const tokensPath = path.join(repoRoot, "design-system/tokens/colors.ts");
const outPath = path.join(repoRoot, "src/app/design-tokens.generated.css");

const { cleanerColors } = await import(tokensPath);

const BANNER = `/*
 * AUTO-GENERATED by scripts/sync-tokens.mjs — DO NOT EDIT.
 * Source: design-system/tokens/colors.ts
 * Run \`npm run sync-tokens\` to regenerate.
 */`;

/**
 * Emits the --cleaner-* variable block for a given mode.
 * Matches the variable names the cleaner UI already consumes via
 * var(--cleaner-*) in globals.css + cleaner-ui.tsx.
 */
function emitCleanerVars(mode) {
  const c = cleanerColors[mode];
  return [
    `  --cleaner-bg: ${c.bg};`,
    `  --cleaner-surface: ${c.surface};`,
    `  --cleaner-ink: ${c.ink};`,
    `  --cleaner-muted: ${c.muted};`,
    `  --cleaner-primary: ${c.primary};`,
    `  --cleaner-primary-soft: ${c.primarySoft};`,
    `  --cleaner-shadow: ${c.shadow};`,
  ].join("\n");
}

const css = [
  BANNER,
  "",
  ":root {",
  emitCleanerVars("light"),
  "}",
  "",
  ".dark {",
  emitCleanerVars("dark"),
  "}",
  "",
].join("\n");

const mode = process.argv[2];

if (mode === "--check") {
  let current;
  try {
    current = readFileSync(outPath, "utf8");
  } catch {
    console.error(`[sync-tokens] ${outPath} is missing. Run \`npm run sync-tokens\`.`);
    process.exit(1);
  }
  if (current !== css) {
    console.error(
      `[sync-tokens] ${path.relative(repoRoot, outPath)} is out of sync with tokens.\n` +
        `             Run \`npm run sync-tokens\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`[sync-tokens] ${path.relative(repoRoot, outPath)} is up to date.`);
  process.exit(0);
}

writeFileSync(outPath, css, "utf8");
console.log(`[sync-tokens] wrote ${path.relative(repoRoot, outPath)}`);
